server:
  port: 9091

spring:
  application:
    name: template
  profiles:
    # 默认激活dev环境
    active: dev
    # 包含了通用的context环境
    include: context
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

LOG_PATH: /.logs

mybatis:
  mapper-locations:
    - "classpath:mapper/**/*.xml"
  configuration:
    mapUnderscoreToCamelCase: true
