server:
  port: 9091

spring:
  application:
    name: template
  profiles:
    # 默认激活dev环境
    active: dev
    # 包含了通用的context环境
    include: context
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

# 你的数据库连接信息所在的位置
datasource:
  config-path: classpath:static

mybatis:
  mapper-locations:
    - "classpath:mapper/**/*.xml"
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    web: debug
    com.ader1y.template: debug
