server:
  port: 9091

spring:
  profiles:
    active: dev
    include: context
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  application:
    name: template

mybatis:
  mapper-locations:
    - "classpath:mapper/**/*.xml"
  configuration:
    mapUnderscoreToCamelCase: true
